# Generated by Django 6.0.6 on 2026-06-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, verbose_name='Company')),
                ('title', models.CharField(max_length=256, verbose_name='Job Title')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='Location')),
                ('remote_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='remote', max_length=20, verbose_name='Remote Type')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Salary Min')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Salary Max')),
                ('status', models.CharField(choices=[('monitoring', 'Monitoring'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('passed', 'Passed'), ('rejected', 'Rejected')], default='monitoring', max_length=20, verbose_name='Status')),
                ('fit_score', models.IntegerField(blank=True, help_text='0-100', null=True, verbose_name='Fit Score')),
                ('source_url', models.URLField(blank=True, verbose_name='URL')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Date Addedd')),
                ('date_applied', models.DateField(blank=True, null=True, verbose_name='Date Applied')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
